{
  "formatVersion": "1.1",
  "component": {
    "group": "io.idnow.trustplatform",
    "module": "core",
    "version": "0.2.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "externalReleaseVariantExternalReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.2.0-beta.aar",
          "url": "core-0.2.0-beta.aar",
          "size": 199048,
          "sha512": "4a0e5623f0a0e3834e5398712b809c100357610691788ae2c8c6a86de26805ca49bac4dc1bf7c858e9c85fdac9e84fc7c649ea2289cf313b2d7150e80c4a15d1",
          "sha256": "cad160ff7d4179320c72db3554a480e89253486663cd323c6dda08b523481f66",
          "sha1": "4d427753512da664152df475b94eb94f0534bb41",
          "md5": "a707484be3306a80a4f3a46ab6a26f73"
        }
      ]
    },
    {
      "name": "externalReleaseVariantExternalReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.idnow.trustplatform",
          "module": "common",
          "version": {
            "requires": "0.2.0-beta"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.2.0-beta.aar",
          "url": "core-0.2.0-beta.aar",
          "size": 199048,
          "sha512": "4a0e5623f0a0e3834e5398712b809c100357610691788ae2c8c6a86de26805ca49bac4dc1bf7c858e9c85fdac9e84fc7c649ea2289cf313b2d7150e80c4a15d1",
          "sha256": "cad160ff7d4179320c72db3554a480e89253486663cd323c6dda08b523481f66",
          "sha1": "4d427753512da664152df475b94eb94f0534bb41",
          "md5": "a707484be3306a80a4f3a46ab6a26f73"
        }
      ]
    }
  ]
}
