{
  "formatVersion": "1.1",
  "component": {
    "group": "io.idnow.design-system.android",
    "module": "sunflower",
    "version": "1.2.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sunflower-1.2.29.aar",
          "url": "sunflower-1.2.29.aar",
          "size": 786799,
          "sha512": "c71072595af948102ee22dce0df8e3898067d044183ea584d03d51406d22a6e3d62060a4eff58e361397b435f42c2540c60701c7868edb34bca3e6f1699d543e",
          "sha256": "d214dbfe2a440af8c4743479a23da3c523dee46fdd66bc7c20680fa0dae6dd34",
          "sha1": "3510530139ccbc07747e1b03b447878efe39abbf",
          "md5": "c119ed10cc14d37582c23224be3cd9d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sunflower-1.2.29.aar",
          "url": "sunflower-1.2.29.aar",
          "size": 786799,
          "sha512": "c71072595af948102ee22dce0df8e3898067d044183ea584d03d51406d22a6e3d62060a4eff58e361397b435f42c2540c60701c7868edb34bca3e6f1699d543e",
          "sha256": "d214dbfe2a440af8c4743479a23da3c523dee46fdd66bc7c20680fa0dae6dd34",
          "sha1": "3510530139ccbc07747e1b03b447878efe39abbf",
          "md5": "c119ed10cc14d37582c23224be3cd9d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sunflower-1.2.29-sources.jar",
          "url": "sunflower-1.2.29-sources.jar",
          "size": 169113,
          "sha512": "803c2a43b3b5e7a4fe366c17a2ab59de83aacf2f2b77fd0011f5200a043ee11f494765f601fcbf99ca895c9d9bb964a07108a1afdf78526fc6e41ec45665f22e",
          "sha256": "db1d3e78f21858202f3433167c8021bc4c0f5e81fb1c5c39850b6d2872ebab69",
          "sha1": "0d574de420dfa8c53f1e4a5060ac835045b89af2",
          "md5": "071dc6b0964300b471cc4aa114febccb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sunflower-1.2.29-javadoc.jar",
          "url": "sunflower-1.2.29-javadoc.jar",
          "size": 1452427,
          "sha512": "883a17da3cf849a43fcf38d4f8dd979bee05376c0e8f40484bc975360b389d2c2dfe826170dc9060b33ff5d9c959b475fe22a23956e97b24ae28e2247b205185",
          "sha256": "1a137d21633389bd36b765c3bc8b4b516ac46b70e927cbe4dc732882f0f44440",
          "sha1": "d7bed4124e11c915e302d8ced737a6f6592acca5",
          "md5": "b726ffdd38887221822d16a6cc39a563"
        }
      ]
    }
  ]
}
