{
  "formatVersion": "1.1",
  "component": {
    "group": "io.idnow.design-system.android",
    "module": "sunflower",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sunflower-1.2.3.aar",
          "url": "sunflower-1.2.3.aar",
          "size": 596391,
          "sha512": "776c5b3749ce161200bd0a6ec804775ef66402f7141214e9c454191bf1caaf3d999acd06cbff9714f165f9ebc19828e697552ba4027f3a69dfdd34adca8decb7",
          "sha256": "a3a321e85dfe70462731143007bcc9c2d5d3f06a84262dfa4392753099999e70",
          "sha1": "3bfa6e63722c043524cf2a7713fdc2cd20afb055",
          "md5": "99df649ba74d5b0bf43f055ed18ff618"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sunflower-1.2.3.aar",
          "url": "sunflower-1.2.3.aar",
          "size": 596391,
          "sha512": "776c5b3749ce161200bd0a6ec804775ef66402f7141214e9c454191bf1caaf3d999acd06cbff9714f165f9ebc19828e697552ba4027f3a69dfdd34adca8decb7",
          "sha256": "a3a321e85dfe70462731143007bcc9c2d5d3f06a84262dfa4392753099999e70",
          "sha1": "3bfa6e63722c043524cf2a7713fdc2cd20afb055",
          "md5": "99df649ba74d5b0bf43f055ed18ff618"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sunflower-1.2.3-sources.jar",
          "url": "sunflower-1.2.3-sources.jar",
          "size": 134459,
          "sha512": "e0c7e49871a91864b47351ed02dce7269430ac2b0dfe080afcbb7bda03750efb14cbae9c5e7b082f5992b89f171a8b63e0e20cd39b07482039caca918e3799f0",
          "sha256": "7695129fca5a3df46ef04feb42edda3f39aa36e37ddafe231ed7e85ea17e8ece",
          "sha1": "e5dba00ee8c58f25e8a1f8a8d4802e58c922d2f8",
          "md5": "5d2876691f09e3ed0b306728716c3d92"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sunflower-1.2.3-javadoc.jar",
          "url": "sunflower-1.2.3-javadoc.jar",
          "size": 1193750,
          "sha512": "d6499cbd1cca00302cf96a6a67f1a10f5364a9319d820b050e5038fc2f5753b4c66cd873cdb80511a338223f0bef2eb3688b6a21bf0bad4cb695d444ad538070",
          "sha256": "19181e19fc55640e54bd14b99d13605a6ca2b63c88e09490ec2a259ed5f8d4c0",
          "sha1": "8b87152f49f76b5eb81d51d7a4560d7398c3ba50",
          "md5": "c71603f4278c8c7fd10ff66fee688a27"
        }
      ]
    }
  ]
}
