{
  "formatVersion": "1.1",
  "component": {
    "group": "io.idnow.design-system.android",
    "module": "sunflower",
    "version": "2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie-compose",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sunflower-2.0.3.aar",
          "url": "sunflower-2.0.3.aar",
          "size": 1340363,
          "sha512": "81b6f9148ddfa44b25817cf63a46539e129c82ae555382bc596cdd10e90a3b0fdfeb86705688dc877a49f69a278efc67b74cc7d75eb5aefde73adbc5e5149446",
          "sha256": "a60c2b280c8c6576f96f2b9b8c866b9bcf442130ab37f1c81e46a46197d4e540",
          "sha1": "9c8c6014f7de420a571844f40a41f18030e475e8",
          "md5": "34bfc95ec979b1315b71df998081f160"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie-compose",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sunflower-2.0.3.aar",
          "url": "sunflower-2.0.3.aar",
          "size": 1340363,
          "sha512": "81b6f9148ddfa44b25817cf63a46539e129c82ae555382bc596cdd10e90a3b0fdfeb86705688dc877a49f69a278efc67b74cc7d75eb5aefde73adbc5e5149446",
          "sha256": "a60c2b280c8c6576f96f2b9b8c866b9bcf442130ab37f1c81e46a46197d4e540",
          "sha1": "9c8c6014f7de420a571844f40a41f18030e475e8",
          "md5": "34bfc95ec979b1315b71df998081f160"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sunflower-2.0.3-sources.jar",
          "url": "sunflower-2.0.3-sources.jar",
          "size": 271973,
          "sha512": "f9d17ebcfb9e90e0625cf69a0501ab821bbf07e24a0d63328368053b34eb9d0a2de36babd24e48ec9378af12d21143b5d1171de3754cd0b8fc3076dae550c7c0",
          "sha256": "784ea01cc0c56cdfccae107a5e123ebfadbe8a6152ae8b9dfad749181d6d8637",
          "sha1": "a00149d1d554b9e787ceb5a6d591ed25bdeb33f6",
          "md5": "4f940155b1ee920cad878439f0c0bceb"
        }
      ]
    }
  ]
}
