{
  "formatVersion": "1.1",
  "component": {
    "group": "io.idnow.nfcreader",
    "module": "nfcreader-ux",
    "version": "1.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "prodReleaseVariantProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "nfcreader-ux-1.3.6.aar",
          "url": "nfcreader-ux-1.3.6.aar",
          "size": 525225,
          "sha512": "7916639abca74cc7b928845e9751d9983fe3e4dc6a31bad0e194cefbb385a5d0b1733ad9a7172b911bcde6be08f3ba21bb03e833d279653c3b8a6b5216de8cc5",
          "sha256": "cf36a8fb5c4a9f711c59f4709da14c88935e5fbda2ba26d9d4f88fb2ec7a3d1e",
          "sha1": "f0456e835bb00307c309419b9e5a926976510ea6",
          "md5": "7b2617593be2ed56216def7a3a41cece"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "io.idnow.nfcreader",
          "module": "nfcreader",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.idnow.design-system.android",
          "module": "sunflower",
          "version": {
            "requires": "1.2.16"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.6.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-navigation"
        },
        {
          "group": "org.orbit-mvi",
          "module": "orbit-core",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.orbit-mvi",
          "module": "orbit-viewmodel",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "nfcreader-ux-1.3.6.aar",
          "url": "nfcreader-ux-1.3.6.aar",
          "size": 525225,
          "sha512": "7916639abca74cc7b928845e9751d9983fe3e4dc6a31bad0e194cefbb385a5d0b1733ad9a7172b911bcde6be08f3ba21bb03e833d279653c3b8a6b5216de8cc5",
          "sha256": "cf36a8fb5c4a9f711c59f4709da14c88935e5fbda2ba26d9d4f88fb2ec7a3d1e",
          "sha1": "f0456e835bb00307c309419b9e5a926976510ea6",
          "md5": "7b2617593be2ed56216def7a3a41cece"
        }
      ]
    }
  ]
}
