{
  "formatVersion": "1.1",
  "component": {
    "group": "io.idnow.nfcreader",
    "module": "nfcreader-ux",
    "version": "1.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "prodReleaseVariantProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "nfcreader-ux-1.3.7.aar",
          "url": "nfcreader-ux-1.3.7.aar",
          "size": 525215,
          "sha512": "9d03c8045c400238ff0fd1f68fcc0eaba0fdb7a3e54a7fdbb98fa8ceb5edd4b806fefe4ccbeaf63634d1b21b24dca7de4ab385370955b7ec744e180175b0e3e9",
          "sha256": "f39fdd572d991681ea9f29d0e982bd1ec38f3a30409ac56d1e1240d80ec650d6",
          "sha1": "5a5831544fb4f14821b2ceb1508861a54240af62",
          "md5": "4c7d1e623b8f7dcc65c298c91a7473bf"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "io.idnow.nfcreader",
          "module": "nfcreader",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.idnow.design-system.android",
          "module": "sunflower",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.6.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-navigation"
        },
        {
          "group": "org.orbit-mvi",
          "module": "orbit-core",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.orbit-mvi",
          "module": "orbit-viewmodel",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "nfcreader-ux-1.3.7.aar",
          "url": "nfcreader-ux-1.3.7.aar",
          "size": 525215,
          "sha512": "9d03c8045c400238ff0fd1f68fcc0eaba0fdb7a3e54a7fdbb98fa8ceb5edd4b806fefe4ccbeaf63634d1b21b24dca7de4ab385370955b7ec744e180175b0e3e9",
          "sha256": "f39fdd572d991681ea9f29d0e982bd1ec38f3a30409ac56d1e1240d80ec650d6",
          "sha1": "5a5831544fb4f14821b2ceb1508861a54240af62",
          "md5": "4c7d1e623b8f7dcc65c298c91a7473bf"
        }
      ]
    }
  ]
}
