{
  "formatVersion": "1.1",
  "component": {
    "group": "io.idnow.design-system.android",
    "module": "sunflower",
    "version": "2.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie-compose",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sunflower-2.0.4.aar",
          "url": "sunflower-2.0.4.aar",
          "size": 1370726,
          "sha512": "744f76f00448a27b15c60c9ed258481e91f38ac4ec948e4d7037efcf97ae1f1d28ce8b816cde82deed343d41663058046b5797ad16c39be1a24edc9f3db244b7",
          "sha256": "d999ce67b221e2bc3fa5d6c04dd2fad15e683325e3315300f78cf617577be49a",
          "sha1": "15b492b19f5e65cdaee0f3929cdd5f5c141cc4cf",
          "md5": "ed303ca394c08b73f688a35e44862e42"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie-compose",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sunflower-2.0.4.aar",
          "url": "sunflower-2.0.4.aar",
          "size": 1370726,
          "sha512": "744f76f00448a27b15c60c9ed258481e91f38ac4ec948e4d7037efcf97ae1f1d28ce8b816cde82deed343d41663058046b5797ad16c39be1a24edc9f3db244b7",
          "sha256": "d999ce67b221e2bc3fa5d6c04dd2fad15e683325e3315300f78cf617577be49a",
          "sha1": "15b492b19f5e65cdaee0f3929cdd5f5c141cc4cf",
          "md5": "ed303ca394c08b73f688a35e44862e42"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sunflower-2.0.4-sources.jar",
          "url": "sunflower-2.0.4-sources.jar",
          "size": 273738,
          "sha512": "8e7f41e8204fdbfd12d60150a736a03ae12e504b99a27664935265d3181cc65017ba682d21f8889674f0db1ec1dbf6e0e177aeb0dfeb6e9c21c2b603b4e2deeb",
          "sha256": "2829716945e9b7994e857b5cce5154cedc58b6f4eb12cc68fdc70c6762b48b84",
          "sha1": "90113695c4a36353de30d11940ea82a661a812b6",
          "md5": "259bcf9dac5796209a765683cddc8dea"
        }
      ]
    }
  ]
}
