{
  "formatVersion": "1.1",
  "component": {
    "group": "io.idnow.trustplatform",
    "module": "core",
    "version": "0.2.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "externalReleaseVariantExternalReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.2.1-beta.aar",
          "url": "core-0.2.1-beta.aar",
          "size": 199048,
          "sha512": "fcd7ef17ea3d4151af3a1106faabf61b204c63b3e0cd92046ddb0f2904f5ea5337495cce7ff6f4cd8483e4f3aea89843eb334718a6b8969b2f054a9e4263429a",
          "sha256": "4fdb9814c64cfe6384cf73b8d1a08aaecf7c3f1795b634add5006314ecb632bf",
          "sha1": "551373961df3444cea51c549291677b9aca7f70f",
          "md5": "8a9b71768eaec32913d287f4f3e51d7f"
        }
      ]
    },
    {
      "name": "externalReleaseVariantExternalReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.idnow.trustplatform",
          "module": "common",
          "version": {
            "requires": "0.2.1-beta"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.2.1-beta.aar",
          "url": "core-0.2.1-beta.aar",
          "size": 199048,
          "sha512": "fcd7ef17ea3d4151af3a1106faabf61b204c63b3e0cd92046ddb0f2904f5ea5337495cce7ff6f4cd8483e4f3aea89843eb334718a6b8969b2f054a9e4263429a",
          "sha256": "4fdb9814c64cfe6384cf73b8d1a08aaecf7c3f1795b634add5006314ecb632bf",
          "sha1": "551373961df3444cea51c549291677b9aca7f70f",
          "md5": "8a9b71768eaec32913d287f4f3e51d7f"
        }
      ]
    }
  ]
}
