{
  "formatVersion": "1.1",
  "component": {
    "group": "io.idnow.nfcreader",
    "module": "nfcreader",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "prodReleaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:mode": "prod",
        "mode": "prod",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "nfcreader-1.3.4.aar",
          "url": "nfcreader-1.3.4.aar",
          "size": 326596,
          "sha512": "810fc2f8dfa7389db6fdbdbd5add2922629e9c3f06e9c9b924a8ab132d241441bd89d465f45159648a222f47f11f7edd26837c5b11fb3607a5678d456789f4f3",
          "sha256": "c668ff1fdf5dce234a76f05121b612a0feb48678d4e863d947031799f121aa0d",
          "sha1": "2cb6459a86e505b301b33bfe1bbd57a690ff35dd",
          "md5": "97f4cdd23fd332bf23b133934eeb4ab9"
        }
      ]
    },
    {
      "name": "prodReleaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:mode": "prod",
        "mode": "prod",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "org.jmrtd",
          "module": "jmrtd",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "nfcreader-1.3.4.aar",
          "url": "nfcreader-1.3.4.aar",
          "size": 326596,
          "sha512": "810fc2f8dfa7389db6fdbdbd5add2922629e9c3f06e9c9b924a8ab132d241441bd89d465f45159648a222f47f11f7edd26837c5b11fb3607a5678d456789f4f3",
          "sha256": "c668ff1fdf5dce234a76f05121b612a0feb48678d4e863d947031799f121aa0d",
          "sha1": "2cb6459a86e505b301b33bfe1bbd57a690ff35dd",
          "md5": "97f4cdd23fd332bf23b133934eeb4ab9"
        }
      ]
    },
    {
      "name": "prodReleaseSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:mode": "prod",
        "mode": "prod",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      }
    }
  ]
}
