{
  "formatVersion": "1.1",
  "component": {
    "group": "io.idnow.nfcreader",
    "module": "nfcreader",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "prodReleaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:mode": "prod",
        "mode": "prod",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "nfcreader-1.5.0.aar",
          "url": "nfcreader-1.5.0.aar",
          "size": 359717,
          "sha512": "786c41f6b91eff9a157d46f906f2f76c964489a3057df100b46271f3e49cbfe8b7fe929f11bb5f51a6f76d7b09a4acaac1135937959f0694f3a6f077b2d613b0",
          "sha256": "a4a82d548a3d59fce1ca6e94a0b0434c727693e0d6f62c75a3242aec9e849f70",
          "sha1": "aa934527e80b6a3e64174ee4e42751659967f82a",
          "md5": "74c01d485b7f3bd5c8d35488f83fa30f"
        }
      ]
    },
    {
      "name": "prodReleaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:mode": "prod",
        "mode": "prod",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "org.jmrtd",
          "module": "jmrtd",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "nfcreader-1.5.0.aar",
          "url": "nfcreader-1.5.0.aar",
          "size": 359717,
          "sha512": "786c41f6b91eff9a157d46f906f2f76c964489a3057df100b46271f3e49cbfe8b7fe929f11bb5f51a6f76d7b09a4acaac1135937959f0694f3a6f077b2d613b0",
          "sha256": "a4a82d548a3d59fce1ca6e94a0b0434c727693e0d6f62c75a3242aec9e849f70",
          "sha1": "aa934527e80b6a3e64174ee4e42751659967f82a",
          "md5": "74c01d485b7f3bd5c8d35488f83fa30f"
        }
      ]
    },
    {
      "name": "prodReleaseSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:mode": "prod",
        "mode": "prod",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      }
    }
  ]
}
