{
  "formatVersion": "1.1",
  "component": {
    "group": "io.idnow.design-system.android",
    "module": "sunflower",
    "version": "1.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sunflower-1.2.7.aar",
          "url": "sunflower-1.2.7.aar",
          "size": 639351,
          "sha512": "7c418e67871840e4c31d4d41a046990b9e7208c43bbfb978a4fe91f2bae2c3231a9be651dbf2f525bc32fa95dda0be47602ea2891c9b94bfdcbfd1a781ec564a",
          "sha256": "3486bb3ca434802109cd23bc28ee38ce2ab2960cc191530690c01a9a431aba22",
          "sha1": "fc1969da391d8daa9f64b167df238a7a49835e45",
          "md5": "c6d4024ede98d8eedfd7c0f4b277f665"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sunflower-1.2.7.aar",
          "url": "sunflower-1.2.7.aar",
          "size": 639351,
          "sha512": "7c418e67871840e4c31d4d41a046990b9e7208c43bbfb978a4fe91f2bae2c3231a9be651dbf2f525bc32fa95dda0be47602ea2891c9b94bfdcbfd1a781ec564a",
          "sha256": "3486bb3ca434802109cd23bc28ee38ce2ab2960cc191530690c01a9a431aba22",
          "sha1": "fc1969da391d8daa9f64b167df238a7a49835e45",
          "md5": "c6d4024ede98d8eedfd7c0f4b277f665"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sunflower-1.2.7-sources.jar",
          "url": "sunflower-1.2.7-sources.jar",
          "size": 143327,
          "sha512": "dc04cf78bc2e796b01dc9282f6c21cd259a091fe90b6e7105f230228b00473c61683b0508a2bb16f747a2a478d2128f6edbadb0f5d74cd6be10749f79620c24a",
          "sha256": "2795e3fefa3053e15810080d07ffb24ced1252ba12a100ab419bcca0e4a4e9ba",
          "sha1": "f3a0c37dac0285d384aec940519270baeecfe0fc",
          "md5": "4e0d50ac3b192eb5399e528a447a9ced"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sunflower-1.2.7-javadoc.jar",
          "url": "sunflower-1.2.7-javadoc.jar",
          "size": 1217484,
          "sha512": "173e6e80c72e91d0446661d1ac6bab263fc59d845b16f3ce7145f12868ab57292e4ec6d38594333e29b205503ee8e041922c6ee1fae79f76b4aba8d7da9373c5",
          "sha256": "43392f85f792543a69be2e9767ef22aa4e7780f02f45edd374ead053d91df24c",
          "sha1": "0098129d523ffa8ef6c7c71a0f3d3fe2233ae0d4",
          "md5": "aca76618a5510aa78fb2c728c1710741"
        }
      ]
    }
  ]
}
