{
  "formatVersion": "1.1",
  "component": {
    "group": "io.idnow.design-system.android",
    "module": "sunflower",
    "version": "2.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie-compose",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sunflower-2.0.5.aar",
          "url": "sunflower-2.0.5.aar",
          "size": 1406047,
          "sha512": "2b618c84d9d169a317cdbce18c8b4c43448dbdf4a67dd9bf68c2a67430458498ba468393836b353eef8e0bbb8e8d15c78888e5e7fb0f5d07194c7435ffaf52d6",
          "sha256": "a74ed910be3209f308350b762b25f997b5f9c783a911397fd7b483598cd32353",
          "sha1": "88035940b345bb63b7f92a6cdf64685e49e2ec8a",
          "md5": "3b126344194ae46d8080daa2d7125a3a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie-compose",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sunflower-2.0.5.aar",
          "url": "sunflower-2.0.5.aar",
          "size": 1406047,
          "sha512": "2b618c84d9d169a317cdbce18c8b4c43448dbdf4a67dd9bf68c2a67430458498ba468393836b353eef8e0bbb8e8d15c78888e5e7fb0f5d07194c7435ffaf52d6",
          "sha256": "a74ed910be3209f308350b762b25f997b5f9c783a911397fd7b483598cd32353",
          "sha1": "88035940b345bb63b7f92a6cdf64685e49e2ec8a",
          "md5": "3b126344194ae46d8080daa2d7125a3a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sunflower-2.0.5-sources.jar",
          "url": "sunflower-2.0.5-sources.jar",
          "size": 284168,
          "sha512": "5566c0677c52182fac9c0593e3983fdf3accf6c5effe85f4bee40ae7329de104817626197afac58182496028d41a73b7e3fa2440609b2e114de140ea0694ff74",
          "sha256": "c30ff78922d2faa05c0315a989c6d03baf2d70242b981d34c55910f1b7901a61",
          "sha1": "85b724722cb20e3a144722ecb36e1a1951eaa907",
          "md5": "97a74116ce404fcdd3e5675d97428658"
        }
      ]
    }
  ]
}
