{
  "formatVersion": "1.1",
  "component": {
    "group": "io.idnow.eid.android",
    "module": "eid-sdk",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "authadaReleaseVariantAuthadaReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "eid-sdk-1.2.2.aar",
          "url": "eid-sdk-1.2.2.aar",
          "size": 1353815,
          "sha512": "c7bd024c2e46bebf097e7691f6657b24027a691c465635defb1ee2ee00eb5c88acbf95ba729143999bc94246a457bfa35daed114a2b49653f8dfd3a1e59ef47e",
          "sha256": "efe0ef9b2a9aaaa8dc61d6f8953e1323c56c78788c87098ad3b52b2fcc41e65b",
          "sha1": "f8aa66a740687753062fd4fe4877ef27091dc84d",
          "md5": "0f04535a12c954a35426ed2d08b97f87"
        }
      ]
    },
    {
      "name": "authadaReleaseVariantAuthadaReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.authada.library",
          "module": "aal",
          "version": {
            "requires": "4.24.4"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.7"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.7"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.9"
          }
        },
        {
          "group": "io.idnow.design-system.android",
          "module": "sunflower",
          "version": {
            "requires": "1.2.31"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.7.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.59.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "eid-sdk-1.2.2.aar",
          "url": "eid-sdk-1.2.2.aar",
          "size": 1353815,
          "sha512": "c7bd024c2e46bebf097e7691f6657b24027a691c465635defb1ee2ee00eb5c88acbf95ba729143999bc94246a457bfa35daed114a2b49653f8dfd3a1e59ef47e",
          "sha256": "efe0ef9b2a9aaaa8dc61d6f8953e1323c56c78788c87098ad3b52b2fcc41e65b",
          "sha1": "f8aa66a740687753062fd4fe4877ef27091dc84d",
          "md5": "0f04535a12c954a35426ed2d08b97f87"
        }
      ]
    },
    {
      "name": "authadaReleaseVariantAuthadaReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "eid-sdk-1.2.2-javadoc.jar",
          "url": "eid-sdk-1.2.2-javadoc.jar",
          "size": 1163106,
          "sha512": "486636ea3f1d63e5fed9875efef6995bac13d8ee1c9314579d3b152b1277f16f121355ec826208576d16ef9c3230b6f96c888425d771a11bcd47f7619fffb561",
          "sha256": "7b0debfab3b0a3897887099f7fef3641f2f42fba870f31ad44a43bec7c0ece1d",
          "sha1": "1295d9782c58d9b32e0282ce2fc9d59669d3f796",
          "md5": "71e84b754b4bf76b786fa2ca4d6cd465"
        }
      ]
    }
  ]
}
