{
  "formatVersion": "1.1",
  "component": {
    "group": "io.idnow.design-system.android",
    "module": "sunflower",
    "version": "1.2.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sunflower-1.2.33.aar",
          "url": "sunflower-1.2.33.aar",
          "size": 831725,
          "sha512": "8fd72b49528db2417c98b0333b3ade2dade5ae144ecf836ff6bf0eba01269fddc19c78e3e15c7cce8b3880069c02752a615c13294be3a836374287bc9d576f7d",
          "sha256": "78010a9f1eb63fa7cf4147912a4d467a832685b46ad5f729aed669211da525cd",
          "sha1": "eb95fa23ee53cf1d0c5bbaa66ef7d170451f5ad8",
          "md5": "7bd9f3c805ccea63af8e6fed6f00b030"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sunflower-1.2.33.aar",
          "url": "sunflower-1.2.33.aar",
          "size": 831725,
          "sha512": "8fd72b49528db2417c98b0333b3ade2dade5ae144ecf836ff6bf0eba01269fddc19c78e3e15c7cce8b3880069c02752a615c13294be3a836374287bc9d576f7d",
          "sha256": "78010a9f1eb63fa7cf4147912a4d467a832685b46ad5f729aed669211da525cd",
          "sha1": "eb95fa23ee53cf1d0c5bbaa66ef7d170451f5ad8",
          "md5": "7bd9f3c805ccea63af8e6fed6f00b030"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sunflower-1.2.33-sources.jar",
          "url": "sunflower-1.2.33-sources.jar",
          "size": 171659,
          "sha512": "f122af628311d86a7f3647f92519256a3ca0be5b13190293d91a090275f43d8f0a6c8b2f8f12a00d3db0652ee293803715b3114bcc574054b6758f2ef43716e1",
          "sha256": "19ef134be0089fb67f7437440cf006db3580b54e322bf4e740768080437f4e6a",
          "sha1": "376f261500a9ed5e47a8d10e6fadb5db080db3dd",
          "md5": "a274119b467c93688d6d86c3e006a755"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sunflower-1.2.33-javadoc.jar",
          "url": "sunflower-1.2.33-javadoc.jar",
          "size": 1452415,
          "sha512": "3f2eac1b86ce5d72fa6fba914dde808a18951ccbba8744c1969ff5b13cca1661891316e4b33c04ecabbada4af3fe7f56dac7293c67892eeebea2fb0bf2728ca5",
          "sha256": "e64640bd916f11cd673a9cadb669ea57b626aa56d301006cae3e0397f5ecedbf",
          "sha1": "70e6da777ef16eff258c81948f12a88447196220",
          "md5": "0b8279e80dd5aeb762689199dee78ef2"
        }
      ]
    }
  ]
}
